### ISSUE TITLE
Some elements are not visible

### ISSUE THREAD

**Issue by sheepymeh** [johnendz/Firefox-Extension-Whatsapp-Dark#1]
# Pins, stickers, videos, and images
```css
.status-sticker svg, .status-video svg, .status-image, [data-icon="pinned"] svg {
    filter: invert();
}
```

Original:  
![image](https://user-images.githubusercontent.com/26665333/73134139-0e606500-406e-11ea-9ca4-98f86d191763.png)
Fixed:  
![image](https://user-images.githubusercontent.com/26665333/73134153-3e0f6d00-406e-11ea-815d-838cb4a73c09.png)

# Link previews (sending)
```css
._1ebw2, .OWYLS {
    background-color: var(--color-background) !important
}
```
Original:  
![image](https://user-images.githubusercontent.com/26665333/73134333-47013e00-4070-11ea-834c-3a05a71b08cc.png)

Fixed:  
![image](https://user-images.githubusercontent.com/26665333/73134267-8bd8a500-406f-11ea-9bb5-2a592c131711.png)

# Link previews (message)
```css
._1SsXF._1AUdd {
    background-color: #006064 !important;
}
```
Original:  
![image](https://user-images.githubusercontent.com/26665333/73134347-89c31600-4070-11ea-815c-f9e6d9fa4f35.png)

Fixed:  
![image](https://user-images.githubusercontent.com/26665333/73134331-3d77d600-4070-11ea-8d2f-a26ec7d492d1.png)

# Send button
```css
._3M-N- {
    filter: invert();
}
```
Original:  
![image](https://user-images.githubusercontent.com/26665333/73134327-3224aa80-4070-11ea-93d5-d80c84f15de0.png)
Fixed:  
![image](https://user-images.githubusercontent.com/26665333/73134268-97c46700-406f-11ea-955d-e07885cb74d2.png)

# Enhancement: unread marker (less bright)
```css
.P6z4j {
    background-color: #006064 !important;
}
```
Original:  
![image](https://user-images.githubusercontent.com/26665333/73134400-0655f480-4071-11ea-89ee-e7d6bd25c6b2.png)
Enhanced:  
![image](https://user-images.githubusercontent.com/26665333/73134406-140b7a00-4071-11ea-90ee-db67c5c925fc.png)
